### ISSUE TITLE
Used at collections.artsmia.org

### ISSUE THREAD

**Issue by kjell** [goodformandspectacle/dimension-drawer#1]
I wanted to leave a note that "drawers" have been added to the Minneapolis Institute of Art's collection site. Thanks for the gem!

https://github.com/artsmia/artwork-dimensions
http://collections.artsmia.org/art/117375/roosters-hen-and-chicks-ito-jakuchu

**Comment by george08** [comment]
@kjell Hi! This is fantastic news! Anything we can do to help?

**Comment by kjell** [comment]
Not really, meaning everything works as promised :+1:

There's one thing I want to take a look at eventually. A lot of our dimension metadata has [multiple dimensions](http://collections.artsmia.org/art/33435/hercules-and-omphale-attributed-to-gerrit-van-honthorst):

```
10 3/4 x 14 13/16 in. (27.31 x 37.62 cm) (sheet)    
11 3/4 x 15 7/8 in. (29.85 x 40.32 cm) (sight)    
19 3/4 x 23 11/16 in. (50.17 x 60.17 cm) (outer frame)
```

It might be more useful to render all three of those in the same "drawer" as "concentric rectangles" vs separately (hover over a dimension and the SVG will swap out).

It shouldn't be hard to draw two rectangles within one another, but it might be a bit harder to mix [two and three dimensions](http://collections.artsmia.org/art/529/lucretia-rembrandt-harmensz-van-rijn) in a cabinet projection:

```
43 3/8 x 36 5/16 in. (110.17 x 92.28 cm) (canvas)
59 1/4 x 52 5/16 x 4 1/2 in. (150.5 x 132.87 x 11.43 cm) (outer frame)
```

And it's even less straightforward, because some objects have multiple dimensions for discrete components that can't "nest" ([hand, body, arm, …](http://collections.artsmia.org/art/5788)).
